name: main
channels:
  - conda-forge
  - nvidia
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=78.1=h33c6efd_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.1=hf4e2dac_1
  - libstdcxx=15.2.0=h934c35e_16
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - python=3.12.12=hd63d673_1_cpython
  - readline=8.3=h853b02a_0
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - anyio==4.12.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - bitsandbytes==0.49.1
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - comm==0.2.3
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.3.3
      - datasets==4.5.0
      - debugpy==1.8.19
      - decorator==5.2.1
      - dill==0.4.0
      - docstring-parser==0.17.0
      - einops==0.8.2
      - executing==2.2.1
      - filelock==3.20.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.3.5
      - idna==3.11
      - ipykernel==7.1.0
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - jedi==0.19.2
      - jinja2==3.1.6
      - jupyter-client==8.7.0
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.7.1
      - multiprocess==0.70.18
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.4.127
      - opencc-python-reimplemented==0.1.7
      - packaging==25.0
      - pandas==3.0.0
      - parso==0.8.5
      - peft==0.18.1
      - pexpect==4.9.0
      - pillow==12.0.0
      - pip==26.0
      - platformdirs==4.5.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==23.0.0
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - regex==2026.1.15
      - requests==2.32.5
      - rich==14.3.2
      - safetensors==0.7.0
      - shellingham==1.5.4
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.13.1
      - tokenizers==0.22.2
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==5.0.0
      - triton==3.2.0
      - trl==0.9.6
      - typeguard==4.4.4
      - typer-slim==0.21.0
      - typing-extensions==4.15.0
      - tyro==1.0.5
      - urllib3==2.6.3
      - wcwidth==0.2.14
      - widgetsnbextension==4.0.15
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /venv/main
